<div class="user_account_container">
  <!--<div class="user_menu">
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Services</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </div> -->

  <div class="user_content">
    <img class="profile" src="../../fahmi/profile.jpg">
    <p>Nama : </p>
    <p>Email : </p>
    <p>Alamat :</p>
    <p>Nomor Telepon :</p>
    <p>Password : </p>
    
  </div>
</div>